/* The following code was generated by JFlex 1.6.1 */

package cminicompiler;

import java_cup.runtime.*;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java.io.Reader;
import java_cup.sym;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/cminicompiler/CMiniLexer.flex</tt>
 */
public class CMiniLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int LINECOMMENT = 4;
  public static final int STRING = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\5\1\64\1\64\1\63\22\0\1\3\1\44\1\20"+
    "\1\53\1\0\1\23\1\55\1\17\1\21\1\22\1\27\1\36\1\45"+
    "\1\37\1\46\1\26\12\2\1\0\1\40\1\41\1\43\1\42\2\0"+
    "\13\1\1\62\1\1\1\60\6\1\1\61\5\1\1\51\1\65\1\52"+
    "\1\0\1\16\1\0\1\13\1\33\1\25\1\24\1\11\1\12\1\1"+
    "\1\32\1\30\1\1\1\57\1\14\1\1\1\31\1\34\2\1\1\7"+
    "\1\15\1\6\1\10\1\35\1\56\3\1\1\47\1\54\1\50\7\0"+
    "\1\64\u1fa2\0\1\64\1\64\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\4\2\2\1\1\5"+
    "\1\6\2\2\1\7\1\10\4\2\1\11\1\12\1\13"+
    "\1\14\1\15\2\1\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\2\1\2\2\1\25\2\4\1\26\1\27"+
    "\1\30\1\31\5\2\2\0\1\32\2\0\1\2\1\33"+
    "\1\2\1\34\1\35\1\36\1\37\5\2\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\2\2\1\46\1\47\1\50"+
    "\1\51\1\52\4\2\1\53\1\54\2\0\2\2\1\55"+
    "\7\2\1\56\1\2\1\57\1\60\1\61\1\2\1\62"+
    "\1\63\1\2\1\64\2\2\1\65\1\2\1\66\2\2"+
    "\1\67\1\2\1\70\1\2\1\71\1\72\1\73\2\2"+
    "\1\74\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\330"+
    "\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4"+
    "\0\330\0\330\0\330\0\u04da\0\u0510\0\u0546\0\u057c\0\330"+
    "\0\330\0\330\0\330\0\330\0\330\0\330\0\u05b2\0\u05e8"+
    "\0\u061e\0\u0654\0\330\0\330\0\u068a\0\330\0\u06c0\0\330"+
    "\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u02be"+
    "\0\330\0\u0870\0\u08a6\0\u08dc\0\u010e\0\u0912\0\330\0\330"+
    "\0\330\0\u010e\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\330"+
    "\0\330\0\330\0\330\0\330\0\330\0\u0a56\0\u0a8c\0\330"+
    "\0\330\0\330\0\330\0\330\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64"+
    "\0\u010e\0\330\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0ca8"+
    "\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u010e\0\u0e22"+
    "\0\u010e\0\330\0\330\0\u0e58\0\u0e8e\0\330\0\u0ec4\0\u010e"+
    "\0\u0efa\0\u0f30\0\u010e\0\u0f66\0\u010e\0\u0f9c\0\u0fd2\0\330"+
    "\0\u1008\0\u010e\0\u103e\0\u010e\0\u010e\0\u010e\0\u1074\0\u10aa"+
    "\0\u010e\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\3\10\1\11\1\12\1\6\1\13"+
    "\1\14\3\6\1\5\1\15\1\16\1\17\1\20\1\5"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\6\1\27"+
    "\1\6\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\6\1\52\2\6\2\53\1\5"+
    "\27\54\1\55\43\54\1\56\60\54\5\57\1\53\12\57"+
    "\1\60\42\57\1\53\1\57\1\61\67\0\2\6\3\0"+
    "\11\6\5\0\2\6\2\0\6\6\20\0\5\6\5\0"+
    "\1\7\66\0\3\10\61\0\2\6\3\0\1\6\1\62"+
    "\7\6\5\0\2\6\2\0\6\6\20\0\5\6\4\0"+
    "\2\6\3\0\3\6\1\63\5\6\5\0\2\6\2\0"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\6\6\1\64"+
    "\2\6\5\0\2\6\2\0\6\6\20\0\5\6\4\0"+
    "\2\6\3\0\5\6\1\65\3\6\5\0\2\6\2\0"+
    "\4\6\1\66\1\6\20\0\5\6\4\0\1\67\1\0"+
    "\1\67\2\0\10\67\6\0\2\67\2\0\6\67\20\0"+
    "\5\67\4\0\1\70\1\0\13\70\2\0\1\71\3\0"+
    "\2\70\2\0\6\70\20\0\5\70\23\0\1\72\2\0"+
    "\1\73\43\0\2\6\3\0\3\6\1\74\5\6\5\0"+
    "\2\6\2\0\4\6\1\75\1\6\20\0\5\6\4\0"+
    "\2\6\3\0\11\6\5\0\2\6\2\0\2\6\1\76"+
    "\3\6\20\0\5\6\31\0\1\77\1\100\64\0\1\101"+
    "\40\0\2\6\3\0\4\6\1\102\4\6\5\0\2\6"+
    "\2\0\1\6\1\103\4\6\20\0\5\6\4\0\2\6"+
    "\3\0\2\6\1\104\6\6\5\0\2\6\2\0\6\6"+
    "\20\0\5\6\4\0\2\6\3\0\1\6\1\105\7\6"+
    "\5\0\2\6\2\0\4\6\1\106\1\6\20\0\5\6"+
    "\4\0\2\6\3\0\11\6\5\0\2\6\2\0\4\6"+
    "\1\107\1\6\20\0\5\6\46\0\1\110\65\0\1\111"+
    "\65\0\1\112\65\0\1\113\76\0\1\114\66\0\1\115"+
    "\11\0\2\6\3\0\11\6\5\0\2\6\2\0\2\6"+
    "\1\116\3\6\20\0\5\6\4\0\2\6\3\0\11\6"+
    "\5\0\2\6\2\0\6\6\20\0\3\6\1\117\1\6"+
    "\31\0\1\120\37\0\5\57\1\0\12\57\1\0\42\57"+
    "\1\0\1\57\7\0\1\121\1\122\10\0\1\123\10\0"+
    "\1\124\35\0\2\6\3\0\2\6\1\125\6\6\5\0"+
    "\2\6\2\0\6\6\20\0\5\6\4\0\2\6\3\0"+
    "\1\126\10\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\7\6\1\127\1\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\4\0\2\6\3\0\6\6"+
    "\1\130\2\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\1\6\1\131\7\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\22\0\1\132\47\0\1\72"+
    "\1\0\13\72\2\0\1\133\3\0\2\72\2\0\6\72"+
    "\20\0\5\72\27\0\2\134\41\0\2\6\3\0\4\6"+
    "\1\135\4\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\5\6\1\136\3\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\4\0\2\6\3\0\1\137"+
    "\10\6\5\0\1\6\1\140\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\6\6\1\141\2\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\4\0\2\6\3\0\3\6"+
    "\1\142\5\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\11\6\5\0\2\6\2\0\4\6"+
    "\1\143\1\6\20\0\5\6\4\0\2\6\3\0\11\6"+
    "\5\0\2\6\2\0\1\144\5\6\20\0\5\6\4\0"+
    "\2\6\3\0\11\6\5\0\2\6\2\0\1\145\5\6"+
    "\20\0\5\6\4\0\2\6\3\0\11\6\5\0\2\6"+
    "\2\0\6\6\20\0\4\6\1\146\4\0\2\6\3\0"+
    "\3\6\1\147\5\6\5\0\2\6\2\0\6\6\20\0"+
    "\5\6\4\0\2\6\3\0\2\6\1\150\6\6\5\0"+
    "\2\6\2\0\6\6\20\0\5\6\4\0\2\6\3\0"+
    "\3\6\1\151\5\6\5\0\2\6\2\0\6\6\20\0"+
    "\5\6\4\0\2\6\3\0\7\6\1\125\1\6\5\0"+
    "\2\6\2\0\6\6\20\0\5\6\25\0\1\152\65\0"+
    "\1\153\44\0\2\6\3\0\11\6\5\0\2\6\2\0"+
    "\1\154\5\6\20\0\5\6\4\0\2\6\3\0\1\6"+
    "\1\155\7\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\11\6\5\0\2\6\1\0\1\156"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\6\6\1\157"+
    "\2\6\5\0\2\6\2\0\6\6\20\0\5\6\4\0"+
    "\2\6\3\0\6\6\1\160\2\6\5\0\2\6\2\0"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\5\6\1\161"+
    "\3\6\5\0\2\6\2\0\6\6\20\0\5\6\4\0"+
    "\2\6\3\0\6\6\1\162\2\6\5\0\2\6\2\0"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\11\6\5\0"+
    "\1\163\1\6\2\0\6\6\20\0\5\6\4\0\2\6"+
    "\3\0\6\6\1\164\2\6\5\0\2\6\2\0\6\6"+
    "\20\0\5\6\4\0\2\6\3\0\11\6\5\0\2\6"+
    "\2\0\6\6\20\0\4\6\1\165\4\0\2\6\3\0"+
    "\1\6\1\166\7\6\5\0\2\6\2\0\6\6\20\0"+
    "\5\6\4\0\2\6\3\0\11\6\5\0\2\6\2\0"+
    "\1\6\1\167\4\6\20\0\5\6\4\0\2\6\3\0"+
    "\11\6\5\0\2\6\1\0\1\170\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\2\6\1\171\6\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\4\0\2\6\3\0\11\6"+
    "\5\0\2\6\2\0\6\6\20\0\1\6\1\172\3\6"+
    "\4\0\2\6\3\0\3\6\1\173\5\6\5\0\2\6"+
    "\2\0\6\6\20\0\5\6\4\0\2\6\3\0\3\6"+
    "\1\174\5\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\11\6\5\0\2\6\2\0\1\6"+
    "\1\175\4\6\20\0\5\6\4\0\2\6\3\0\3\6"+
    "\1\176\5\6\5\0\2\6\2\0\6\6\20\0\5\6"+
    "\4\0\2\6\3\0\11\6\5\0\1\177\1\6\2\0"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\5\6\1\200"+
    "\3\6\5\0\2\6\2\0\6\6\20\0\5\6\4\0"+
    "\2\6\3\0\3\6\1\201\5\6\5\0\2\6\2\0"+
    "\6\6\20\0\5\6\4\0\2\6\3\0\11\6\5\0"+
    "\2\6\2\0\1\6\1\202\4\6\20\0\5\6\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4320];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\12\1\1\11\10\1\3\11\4\1\7\11"+
    "\4\1\2\11\1\1\1\11\1\1\1\11\6\1\2\0"+
    "\1\11\2\0\3\1\3\11\6\1\6\11\2\1\5\11"+
    "\5\1\1\11\2\0\15\1\2\11\2\1\1\11\11\1"+
    "\1\11\12\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    int stComment = 0;
    int commentLine;
    StringBuffer string = new StringBuffer();

    private Symbol symbol(String name, int sym) {
            return new Symbol(sym, yyline, yycolumn);
    }

    private Symbol symbol(String name, int sym, Object val) {
            return new Symbol(sym, yyline, yycolumn, val);
    }

    private void error(String message) {
            System.err.println("Lexical Error at line "+(yyline+1)+", column "+(yycolumn+1)+" : "+message);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CMiniLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 182) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     if(stComment!=0)
            System.out.println("Comment started at line " + commentLine + " is not finished");
    return new Symbol(sym.EOF, yyline, yycolumn);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("No se reconoce el simbolo: "+yytext());
            }
          case 62: break;
          case 2: 
            { System.out.println("ID: "+yytext());
            }
          case 63: break;
          case 3: 
            { System.out.println("INTEGER: "+yytext());
            }
          case 64: break;
          case 4: 
            { 
            }
          case 65: break;
          case 5: 
            { System.out.println("Se econtró: )");
            }
          case 66: break;
          case 6: 
            { System.out.println("Se econtró: (");
            }
          case 67: break;
          case 7: 
            { System.out.println("ARTHM Se econtró: /");
            }
          case 68: break;
          case 8: 
            { System.out.println("ARTHM Se econtró: *");
            }
          case 69: break;
          case 9: 
            { System.out.println("ARTHM Se econtró: +");
            }
          case 70: break;
          case 10: 
            { System.out.println("ARTHM Se econtró: -");
            }
          case 71: break;
          case 11: 
            { System.out.println("Se econtró: ;");
            }
          case 72: break;
          case 12: 
            { System.out.println("BOOL Se econtró: <");
            }
          case 73: break;
          case 13: 
            { System.out.println("BOOL Se econtró: >");
            }
          case 74: break;
          case 14: 
            { System.out.println("Se econtró: ,");
            }
          case 75: break;
          case 15: 
            { System.out.println("Se econtró: .");
            }
          case 76: break;
          case 16: 
            { System.out.println("Se econtró: {");
            }
          case 77: break;
          case 17: 
            { System.out.println("Se econtró: }");
            }
          case 78: break;
          case 18: 
            { System.out.println("Se econtró: [");
            }
          case 79: break;
          case 19: 
            { System.out.println("Se econtró: ]");
            }
          case 80: break;
          case 20: 
            { System.out.println("Se econtró: #");
            }
          case 81: break;
          case 21: 
            { System.out.print(yytext());
            }
          case 82: break;
          case 22: 
            { yybegin(YYINITIAL);
            }
          case 83: break;
          case 23: 
            { string.append( yytext() );
            }
          case 84: break;
          case 24: 
            { string.append( yytext() );
                                       yybegin(YYINITIAL);
                                       System.out.println("String literal: "+ string.toString());
            }
          case 85: break;
          case 25: 
            { string.append('\\');
            }
          case 86: break;
          case 26: 
            { System.out.println("conststr: "+ yytext());
            }
          case 87: break;
          case 27: 
            { System.out.println("TYPE Se econtró: do");
            }
          case 88: break;
          case 28: 
            { yybegin(LINECOMMENT);
            }
          case 89: break;
          case 29: 
            { commentLine = yyline+1; stComment++; yybegin(COMMENT);
            }
          case 90: break;
          case 30: 
            { System.out.println("Utilizó */ sin abrirlo");
            }
          case 91: break;
          case 31: 
            { System.out.println("TYPE EXPR Se econtró: if");
            }
          case 92: break;
          case 32: 
            { System.out.println("BOOL Se econtró: <=");
            }
          case 93: break;
          case 33: 
            { System.out.println("BOOL Se econtró: >=");
            }
          case 94: break;
          case 34: 
            { System.out.println("BOOL Se econtró: ==");
            }
          case 95: break;
          case 35: 
            { System.out.println("BOOL Se econtró: !=");
            }
          case 96: break;
          case 36: 
            { System.out.println("Se econtró: ||");
            }
          case 97: break;
          case 37: 
            { System.out.println("Se econtró: &&");
            }
          case 98: break;
          case 38: 
            { stComment--; if(stComment==0) yybegin(YYINITIAL);
            }
          case 99: break;
          case 39: 
            { string.append('\t');
            }
          case 100: break;
          case 40: 
            { string.append('\r');
            }
          case 101: break;
          case 41: 
            { string.append('\"');
            }
          case 102: break;
          case 42: 
            { string.append('\n');
            }
          case 103: break;
          case 43: 
            { System.out.println("TYPE Se econtró: for");
            }
          case 104: break;
          case 44: 
            { System.out.println("constchar: "+ yytext());
            }
          case 105: break;
          case 45: 
            { System.out.println("Se econtró: int");
            }
          case 106: break;
          case 46: 
            { System.out.println("TRUE|FALSE Se econtró: "+yytext());
            }
          case 107: break;
          case 47: 
            { System.out.println("TYPE EXPR Se econtró: else");
            }
          case 108: break;
          case 48: 
            { System.out.println("Printf: "+yytext());
            }
          case 109: break;
          case 49: 
            { System.out.println("Scanf: "+yytext());
            }
          case 110: break;
          case 50: 
            { System.out.println("Se econtró: char");
            }
          case 111: break;
          case 51: 
            { System.out.println("Se econtró: int*");
            }
          case 112: break;
          case 52: 
            { System.out.println("NULL Se econtró: null");
            }
          case 113: break;
          case 53: 
            { System.out.println("Se econtró: void");
            }
          case 114: break;
          case 54: 
            { System.out.println("NULL Se econtró: NULL");
            }
          case 115: break;
          case 55: 
            { System.out.println("Se econtró: char*");
            }
          case 116: break;
          case 56: 
            { System.out.println("Se econtró: break");
            }
          case 117: break;
          case 57: 
            { System.out.println("TYPE Se econtró: while");
            }
          case 118: break;
          case 58: 
            { System.out.println("Se econtró: return");
            }
          case 119: break;
          case 59: 
            { System.out.println("Se econtró: define");
            }
          case 120: break;
          case 60: 
            { System.out.println("Se econtró: include");
            }
          case 121: break;
          case 61: 
            { System.out.println("Se econtró: boolean");
            }
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java CMiniLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        CMiniLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new CMiniLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
