
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 16 18:07:36 CST 2017
//----------------------------------------------------

package cminicompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 39;
  public static final int SINGLECHAR = 38;
  public static final int STRING_LITERAL = 42;
  public static final int SCANF = 8;
  public static final int CHAR = 3;
  public static final int INT = 2;
  public static final int ARTHMEXPSUM = 9;
  public static final int FOR = 25;
  public static final int BOOLTOF = 35;
  public static final int DEFINE = 30;
  public static final int DECIMALINT = 37;
  public static final int SEMICOLON = 12;
  public static final int AND = 24;
  public static final int OR = 23;
  public static final int COMMA = 14;
  public static final int MAIN = 41;
  public static final int IF = 28;
  public static final int ID = 36;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 32;
  public static final int INT_CONST = 40;
  public static final int error = 1;
  public static final int INCLUDE = 31;
  public static final int RIGHTCBRAC = 19;
  public static final int NULL = 34;
  public static final int RIGHTBRAK = 21;
  public static final int BREAK = 33;
  public static final int VOID = 6;
  public static final int RIGTHPRNTH = 17;
  public static final int PRINTF = 7;
  public static final int LEFTCBRAC = 18;
  public static final int COLON = 13;
  public static final int ELSE = 29;
  public static final int ARTHMEXPMULT = 10;
  public static final int WHILE = 26;
  public static final int NUMERAL = 22;
  public static final int LEFTBRAK = 20;
  public static final int CONSTCHAR = 5;
  public static final int LEFTPRNTH = 16;
  public static final int BOOLEXP = 11;
  public static final int DO = 27;
}

