
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 18 23:28:25 CST 2017
//----------------------------------------------------

package cminicompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SINGLECHAR = 31;
  public static final int SCANF = 8;
  public static final int CHAR = 3;
  public static final int ASTERISK = 35;
  public static final int EQUALS = 18;
  public static final int INTEGER = 32;
  public static final int INT = 2;
  public static final int ARTHMEXPSUM = 9;
  public static final int FOR = 21;
  public static final int BOOLTOF = 28;
  public static final int DECIMALINT = 30;
  public static final int SEMICOLON = 12;
  public static final int AND = 20;
  public static final int OR = 19;
  public static final int COMMA = 13;
  public static final int MAIN = 33;
  public static final int IF = 23;
  public static final int AMPERSAND = 34;
  public static final int ID = 29;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 25;
  public static final int error = 1;
  public static final int RIGHTCBRAC = 17;
  public static final int NULL = 27;
  public static final int CONSTSTR = 36;
  public static final int BREAK = 26;
  public static final int VOID = 6;
  public static final int PRINTF = 7;
  public static final int LEFTCBRAC = 16;
  public static final int ELSE = 24;
  public static final int ARTHMEXPMULT = 10;
  public static final int WHILE = 22;
  public static final int RIGHTPRNTH = 15;
  public static final int CONSTCHAR = 5;
  public static final int LEFTPRNTH = 14;
  public static final int BOOLEXP = 11;
}

